version: "3.7"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "4008:4008"
  rust-embed:
    build:
      context: .
      dockerfile: Dockerfile-rust-embed
    restart: unless-stopped
    ports:
      - "4001:4001"
